### ISSUE TITLE
swig compilation on macOS

### ISSUE THREAD

**Issue by freder** [LingDong-/skeleton-tracing#8]
just FYI: 
I had to add `--undefined dynamic_lookup` to the linker command in `compile.sh` to get it to work on the mac.
what that does exactly is beyond me, but it might be worth adding to the readme to save other people some headache.

**Comment by LingDong-** [comment]
Thanks! I'm on macOS too but did't need the flag, though adding it seems to produce no negative effect. So I'm putting it in `compile.sh` anyways, in case other people run into the same issue. Commit: 607373b69c32f76088f8005ee357ba2dea2b89ce

BTW seems like it should be `-undefined dynamic_lookup` (single dash), otherwise clang does not recognize it.

**Comment by freder** [comment]
👍
